### ISSUE TITLE
Recipe list

### ISSUE THREAD

**Issue by DanShu15** [AlexIIL/SimplePipes#39]
![2020-05-30_22 26 58](https://user-images.githubusercontent.com/40204993/83344481-c0ca6200-a2c4-11ea-9bc3-703850534190.png)
Is it possible to do anything about the facades recipes? Maybe a version with just the pipes themselves?
I appreciate them, but there are hundreds of pages in REI of them and they make REI take a minute or two to load up. I filtered them out hoping it would just forget about them, but unfortunately, the delay to load everything still exists even with the filter in place.
This is on the 1.15.2 one.

Thanks!

**Comment by AlexIIL** [comment]
That's not ideal. I'd recommend opening an issue with REI as simple pipes probably won't be the only mod that adds a large number of possible items. (In addition I'm hesitant to work on simple pipes that much because I'm dedicating a lot of time to buildcraft dev).

On a side note: do you know what mod that "Connected Rammed Earth" block is from? By the looks of things it probably shouldn't be a facade (and similarly, is there a large number of facades with missing textures or useless variants?)

**Comment by DanShu15** [comment]
ok I'll let REI know :)
There was an Exotic Blocks mod that I had to take out because of the huge amount of items too. Rammed earth may be from that mod, or it was in something I removed. Uplands had some new blocks, that might be it.
Np at all on not messing with this one, can't wait for BC :)
Thanks!
