### ISSUE TITLE
Iron Pipes not connecting to containers in 1.16.1

### ISSUE THREAD

**Issue by roquemore92** [AlexIIL/SimplePipes#42]
I noticed that when placing iron pipes in 1.16.1, they will only connect to other pipes, but not other containers like composters, chests, or hoppers. Other pipes (tested diamond, wood, gold, and clay) work fine, as do iron pipes placed during 1.15.2. It's only an issue with iron pipes placed in 1.16.

I tested with all other mods and datapacks removed, so it doesn't seem to be another mod interfering with it.

**Comment by AlexIIL** [comment]
Oh, that's not good :/

However I'm unlikely to look into this *ever* as I'm working on porting buildcraft itself rather than this. However I'll leave this issue open in case someone else wants to find out what's going wrong and fix it.

**Comment by roquemore92** [comment]
It's all good. for the particular area I was using that in, I was able use hoppers as a workaround for the system instead of iron pipes.

Question for your buildcraft port if you have time. Will just the pipes be available standalone once that's available? Still using redstone to power the extraction, rather than machines? I'd been looking for essentially the function of diamond pipes (multiple items sorted into a single chest, basically used as filtered hoppers) that wasn't part of a full game overhaul for a while before I found this.

**Comment by AlexIIL** [comment]
BuildCraft is split up into modules - core, energy, factory, etc. If you only want pipes then you can have *just* pipes by installing the core + transport modules. So would that be enough? (Although buildcraft isn't really a full game overhaul - it's mostly just additions). AFAIK the main difference between BC and simple pipes is you'd have to craft a redstone engine instead of powering wooden pipes with redstone directly.

I'm planning to archive this project after releasing buildcraft, and make all SP stuff turn into their BC equivilents.

**Comment by Kneelawk** [comment]
This bug seems to be related to the fact that TilePipeSided.canConnect(Direction) is only checking if the pipe's current direction is aligned with the direction canConnect is testing for, instead of checking flow.canConnect(Direction) like in TilePipe. This also means that if an Iron Pipe is facing toward a pipe and that pipe is removed, the Iron Pipe will continue being connected in that direction, even though there are no blocks there.

**Comment by Kneelawk** [comment]
The intended behavior may have been to prevent Iron Pipes from connecting to inventories by default and then allow them to connect when their current direction is switched?

**Comment by Kneelawk** [comment]
In TileIronPipe.canFaceDirection(Direction), the Iron Pipe only allows itself to face one of the already connected directions. This means that a new connection cannot be formed by changing the pipe's current direction. I have addressed this in my pull request.
